HEADERS += src/domain/UBGraphicsScene.h \
    src/domain/UBGraphicsItemUndoCommand.h \
    src/domain/UBGraphicsTextItemUndoCommand.h \
    src/domain/UBGraphicsItemTransformUndoCommand.h \
    src/domain/UBGraphicsPixmapItem.h \
    src/domain/UBDocumentUndoCommand.h \
    src/domain/UBPageSizeUndoCommand.h \
    src/domain/UBGraphicsSvgItem.h \
    src/domain/UBGraphicsPolygonItem.h \
    src/domain/UBItem.h \
    src/domain/UBGraphicsWidgetItem.h \
    src/domain/UBGraphicsPDFItem.h \
    src/domain/UBGraphicsTextItem.h \
    src/domain/UBResizableGraphicsItem.h \
    src/domain/UBGraphicsStroke.h \
    src/domain/UBGraphicsMediaItem.h \
    src/domain/UBAbstractUndoCommand.h \
    src/domain/UBGraphicsGroupContainerItem.h \
    src/domain/UBGraphicsGroupContainerItemDelegate.h \
    src/domain/UBGraphicsStrokesGroup.h \
    src/domain/UBGraphicsItemGroupUndoCommand.h \
    src/domain/UBGraphicsItemDelegate.h \
    src/domain/UBGraphicsTextItemDelegate.h \
    src/domain/UBGraphicsDelegateFrame.h \
    src/domain/UBGraphicsWidgetItemDelegate.h \
    src/domain/UBGraphicsMediaItemDelegate.h \
    src/domain/UBGraphicsEllipseItem.h \
    src/domain/UBShapeFactory.h \
    src/domain/UBGraphicsRectItem.h \
    src/domain/UBGraphicsLineItem.h \
    src/domain/UBGraphicsFreehandItem.h \
    src/domain/UBAbstractGraphicsPathItem.h \
    src/domain/UBEditable.h \
    src/domain/UBAbstractHandle.h \
    src/domain/UBDiagonalHandle.h \
    src/domain/UBFreeHandle.h \
    src/domain/UBHorizontalHandle.h \
    src/domain/UBVerticalHandle.h \
    src/domain/UB2HandlesEditable.h \
    src/domain/UB3HandlesEditable.h \
    src/domain/UBShapeEditable.h \
    src/domain/UBAbstractEditableGraphicsPathItem.h \
    src/domain/UBAbstractHandlesBuilder.h \
    src/domain/UB1HEditableGraphicsCircleItem.h \
    src/domain/UB1HEditableGraphicsSquareItem.h \
    src/domain/UBAbstractGraphicsItem.h \
    src/domain/UBEditableGraphicsPolygonItem.h \
    src/domain/UB1HEditableGraphicsBasicShapeItem.h \
    src/domain/UBEditableGraphicsRegularShapeItem.h \
    src/domain/UBAlignObjectManager.h \
    src/domain/UBDragableThumbnail.h \
    src/domain/UBAbstractGraphicsProxyWidget.h \
    src/domain/UBGraphicsProxyWidget.h
    
SOURCES += src/domain/UBGraphicsScene.cpp \
    src/domain/UBGraphicsItemUndoCommand.cpp \
    src/domain/UBGraphicsTextItemUndoCommand.cpp \
    src/domain/UBGraphicsItemTransformUndoCommand.cpp \
    src/domain/UBGraphicsPixmapItem.cpp \
    src/domain/UBDocumentUndoCommand.cpp \
    src/domain/UBPageSizeUndoCommand.cpp \
    src/domain/UBGraphicsSvgItem.cpp \
    src/domain/UBGraphicsPolygonItem.cpp \
    src/domain/UBItem.cpp \
    src/domain/UBGraphicsVideoItem.cpp \
    src/domain/UBGraphicsWidgetItem.cpp \
    src/domain/UBGraphicsPDFItem.cpp \
    src/domain/UBGraphicsTextItem.cpp \
    src/domain/UBResizableGraphicsItem.cpp \
    src/domain/UBGraphicsStroke.cpp \
    src/domain/UBGraphicsMediaItem.cpp \
    src/domain/UBAbstractUndoCommand.cpp \
    src/domain/UBGraphicsGroupContainerItem.cpp \
    src/domain/UBGraphicsGroupContainerItemDelegate.cpp \
    src/domain/UBGraphicsStrokesGroup.cpp \
    src/domain/UBGraphicsItemGroupUndoCommand.cpp \
    src/domain/UBGraphicsItemDelegate.cpp \
    src/domain/UBGraphicsTextItemDelegate.cpp \
    src/domain/UBGraphicsMediaItemDelegate.cpp \
    src/domain/UBGraphicsDelegateFrame.cpp \
    src/domain/UBGraphicsWidgetItemDelegate.cpp \
    src/domain/UBGraphicsEllipseItem.cpp \
    src/domain/UBShapeFactory.cpp \
    src/domain/UBGraphicsRectItem.cpp \
    src/domain/UBGraphicsLineItem.cpp \
    src/domain/UBGraphicsFreehandItem.cpp \
    src/domain/UBAbstractGraphicsPathItem.cpp \
    src/domain/UBAbstractHandle.cpp \
    src/domain/UBEditable.cpp \
    src/domain/UBDiagonalHandle.cpp \
    src/domain/UBFreeHandle.cpp \
    src/domain/UBHorizontalHandle.cpp \
    src/domain/UBVerticalHandle.cpp \
    src/domain/UB2HandlesEditable.cpp \
    src/domain/UB3HandlesEditable.cpp \
    src/domain/UBShapeEditable.cpp \
    src/domain/UBAbstractEditableGraphicsPathItem.cpp \
    src/domain/UBAbstractHandlesBuilder.cpp \
    src/domain/UB1HEditableGraphicsCircleItem.cpp \
    src/domain/UB1HEditableGraphicsBasicShapeItem.cpp \
    src/domain/UB1HEditableGraphicsSquareItem.cpp \
    src/domain/UBAbstractGraphicsItem.cpp \
    src/domain/UBEditableGraphicsPolygonItem.cpp \
    src/domain/UBEditableGraphicsRegularShapeItem.cpp \
    src/domain/UBAlignObjectManager.cpp \
    src/domain/UBDragableThumbnail.cpp \
    src/domain/UBAbstractGraphicsProxyWidget.cpp \
    src/domain/UBGraphicsProxyWidget.cpp
